language: node_js
node_js:
  - 0.10.34
env:
  global:
    - NODE_ENV=travis
    - secure: s2l5ttOwRBCTG7lFG7wyY/6ZcF2G4l65i1YoIAPcRV0HcO5GGYw/Aae2Be1wGuJfAkgEcbDHfFUfZfdIoQkg4fGxGCCxtzT63kW1eWxJyInrpjSzbbgnyJz1FE0GEEwBcjSLPc9wxrb4zO5UccvplUxiZh5ZnLli6ay4r7xdgih6crZb6NSD2A9N3gH5OJtpHFK8a9uuTTutX5jBhpleECHub4m4LTl0FuEZS5OT5rYv9TB5P6AGdaH3kWpYMh9U/5wtgzX5mWceEYGtoE7RlnpGcZPvwKHoo/by0QPpL8npafsK0tOa1kkaHoJxMEuhK0X0b3pJXgCeP3CeG0m8LA==


services:
  - mongodb

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - curl -sSL https://get.docker.com/ubuntu/ | sudo sh
  - sudo sh -c 'echo DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock">>/etc/default/docker'
  - cat /etc/default/docker
  - sudo service docker restart
  - docker -v
  - docker run ubuntu echo hello world


script:
  - grunt test

after_script:
  - env
  - docker login -u $USERNAME -p $PASSWORD -e $EMAIL
  - docker build -t rohitghatol/dashboard-mean-vanilla .
  - docker push rohitghatol/dashboard-mean-vanilla


