language: node_js
node_js:
  - 0.10.34
env:
  - NODE_ENV=travis
services:
  - mongodb

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - grunt test
build_image: dockerfile/nodejs
commit_container: rohitghatol/Dashboard-Mean-Vanilla