language: node_js
node_js:
  - 0.10.34
env:
  - NODE_ENV=travis

build_image: rohitghatol/Dashboard-Mean-Vanilla

services:
  - mongodb

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - grunt test


